server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: interOP@123
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update